export const rows = [ //hour
   { hour: "8-9",   gridArea: "2/1/3/9"},
   { hour: "9-10",  gridArea: "3/1/4/9"},
   { hour: "10-11", gridArea: "4/1/5/9"},
   { hour: "11-12", gridArea: "5/1/6/9"},
   { hour: "12-13", gridArea: "6/1/7/9"},
   { hour: "13-14", gridArea: "7/1/8/9"},
   { hour: "14-15", gridArea: "8/1/9/9"},
   { hour: "15-16", gridArea: "9/1/10/9"},
   { hour: "16-17", gridArea: "10/1/11/9"},
   { hour: "17-18", gridArea: "11/1/12/9"},
   { hour: "18-19", gridArea: "12/1/13/9"},
   { hour: "19-20", gridArea: "13/1/13/9"},
];

export const columns = [ //day
   { day: "شن",   gridArea: "1/2/14/3"},
   { day: "یک",   gridArea: "1/3/14/4"},
   { day: "دو",   gridArea: "1/4/14/5"},
   { day: "سه",   gridArea: "1/5/14/6"},
   { day: "چهار", gridArea: "1/6/14/7"},
   { day: "پنج",  gridArea: "1/7/14/8"},
   { day: "جم",   gridArea: "1/8/14/9"},
];

export const cells = [
   {selected: false,   day: "شن",   dayVal: "1",   hour: "8-9", hourVal: "8",     gridArea: "2/2/3/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "8-9", hourVal: "8",     gridArea: "2/3/3/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "8-9", hourVal: "8",     gridArea: "2/4/3/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "8-9", hourVal: "8",     gridArea: "2/5/3/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "8-9", hourVal: "8",     gridArea: "2/6/3/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "8-9", hourVal: "8",     gridArea: "2/7/3/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "8-9", hourVal: "8",     gridArea: "2/8/3/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "9-10", hourVal: "9",    gridArea: "3/2/4/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "9-10", hourVal: "9",    gridArea: "3/3/4/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "9-10", hourVal: "9",    gridArea: "3/4/4/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "9-10", hourVal: "9",    gridArea: "3/5/4/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "9-10", hourVal: "9",    gridArea: "3/6/4/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "9-10", hourVal: "9",    gridArea: "3/7/4/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "9-10", hourVal: "9",    gridArea: "3/8/4/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "10-11",  hourVal: "10",  gridArea: "4/2/5/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "10-11",  hourVal: "10",  gridArea: "4/3/5/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "10-11",  hourVal: "10",  gridArea: "4/4/5/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "10-11",  hourVal: "10",  gridArea: "4/5/5/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "10-11",  hourVal: "10",  gridArea: "4/6/5/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "10-11",  hourVal: "10",  gridArea: "4/7/5/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "10-11",  hourVal: "10",  gridArea: "4/8/5/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "11-12", hourVal: "11",   gridArea: "5/2/6/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "11-12", hourVal: "11",   gridArea: "5/3/6/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "11-12", hourVal: "11",   gridArea: "5/4/6/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "11-12", hourVal: "11",   gridArea: "5/5/6/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "11-12", hourVal: "11",   gridArea: "5/6/6/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "11-12", hourVal: "11",   gridArea: "5/7/6/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "11-12", hourVal: "11",   gridArea: "5/8/6/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "12-13", hourVal: "12",   gridArea: "6/2/7/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "12-13", hourVal: "12",   gridArea: "6/3/7/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "12-13", hourVal: "12",   gridArea: "6/4/7/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "12-13", hourVal: "12",   gridArea: "6/5/7/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "12-13", hourVal: "12",   gridArea: "6/6/7/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "12-13", hourVal: "12",   gridArea: "6/7/7/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "12-13", hourVal: "12",   gridArea: "6/8/7/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "13-14", hourVal: "13",   gridArea: "7/2/8/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "13-14", hourVal: "13",   gridArea: "7/3/8/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "13-14", hourVal: "13",   gridArea: "7/4/8/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "13-14", hourVal: "13",   gridArea: "7/5/8/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "13-14", hourVal: "13",   gridArea: "7/6/8/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "13-14", hourVal: "13",   gridArea: "7/7/8/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "13-14", hourVal: "13",   gridArea: "7/8/8/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "14-15", hourVal: "14",   gridArea: "8/2/9/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "14-15", hourVal: "14",   gridArea: "8/3/9/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "14-15", hourVal: "14",   gridArea: "8/4/9/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "14-15", hourVal: "14",   gridArea: "8/5/9/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "14-15", hourVal: "14",   gridArea: "8/6/9/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "14-15", hourVal: "14",   gridArea: "8/7/9/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "14-15", hourVal: "14",   gridArea: "8/8/9/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "15-16", hourVal: "15",   gridArea: "9/2/10/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "15-16", hourVal: "15",   gridArea: "9/3/10/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "15-16", hourVal: "15",   gridArea: "9/4/10/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "15-16", hourVal: "15",   gridArea: "9/5/10/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "15-16", hourVal: "15",   gridArea: "9/6/10/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "15-16", hourVal: "15",   gridArea: "9/7/10/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "15-16", hourVal: "15",   gridArea: "9/8/10/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "16-17", hourVal: "16",   gridArea: "10/2/11/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "16-17", hourVal: "16",   gridArea: "10/3/11/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "16-17", hourVal: "16",   gridArea: "10/4/11/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "16-17", hourVal: "16",   gridArea: "10/5/11/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "16-17", hourVal: "16",   gridArea: "10/6/11/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "16-17", hourVal: "16",   gridArea: "10/7/11/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "16-17", hourVal: "16",   gridArea: "10/8/11/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "17-18", hourVal: "17",   gridArea: "11/2/12/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "17-18", hourVal: "17",   gridArea: "11/3/12/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "17-18", hourVal: "17",   gridArea: "11/4/12/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "17-18", hourVal: "17",   gridArea: "11/5/12/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "17-18", hourVal: "17",   gridArea: "11/6/12/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "17-18", hourVal: "17",   gridArea: "11/7/12/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "17-18", hourVal: "17",   gridArea: "11/8/12/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "18-19", hourVal: "18",   gridArea: "12/2/13/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "18-19", hourVal: "18",   gridArea: "12/3/13/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "18-19", hourVal: "18",   gridArea: "12/4/13/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "18-19", hourVal: "18",   gridArea: "12/5/13/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "18-19", hourVal: "18",   gridArea: "12/6/13/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "18-19", hourVal: "18",   gridArea: "12/7/13/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "18-19", hourVal: "18",   gridArea: "12/8/13/9"},
// -----------------   ------------------------   ------------------------------ ---------------------
   {selected: false,   day: "شن",   dayVal: "1",   hour: "19-20", hourVal: "19",   gridArea: "13/2/13/3"},
   {selected: false,   day: "یک",   dayVal: "2",   hour: "19-20", hourVal: "19",   gridArea: "13/3/13/4"},
   {selected: false,   day: "دو",   dayVal: "3",   hour: "19-20", hourVal: "19",   gridArea: "13/4/13/5"},
   {selected: false,   day: "سه",   dayVal: "4",   hour: "19-20", hourVal: "19",   gridArea: "13/5/13/6"},
   {selected: false,   day: "چهار", dayVal: "5",   hour: "19-20", hourVal: "19",   gridArea: "13/6/13/7"},
   {selected: false,   day: "پنج",  dayVal: "6",   hour: "19-20", hourVal: "19",   gridArea: "13/7/13/8"},
   {selected: false,   day: "جم",   dayVal: "7",   hour: "19-20", hourVal: "19",   gridArea: "13/8/13/9"},
];
